Repository Geeky-star/Footer-and-Header-design-Challenge, pull requests merged in 2021-10, with the labels that each got.

#20 chore: add responsive header to collection.
  ResponsiveHeader/Header.css
  ResponsiveHeader/Header.html
  ResponsiveHeader/name.txt
Labels: Open-Source, Hacktoberfest, Hacktoberfest-accepted

#45 added floating footer
  floating-footer/index.html
  floating-footer/name.txt
  floating-footer/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#46 feat: add sticky footer with grid
  sticky-footer-with-grid/index.html
  sticky-footer-with-grid/name.txt
  sticky-footer-with-grid/style.css
Labels: Open-Source, hacktoberfest, hacktoberfest-accepted

#47 Added UniversityFooter
  UniversityFooter/1.jpg
  UniversityFooter/college-view.jpg
  UniversityFooter/iiindex.css
  UniversityFooter/index.html
  UniversityFooter/logo.png
  UniversityFooter/name.txt
Labels: Open-Source, hacktoberfest, hacktoberfest-accepted

#49 simple navbar
  simple-navbar/index.html
  simple-navbar/name.txt
  simple-navbar/sparx.jpg
  simple-navbar/style.css
Labels: Open-Source, hacktoberfest, hacktoberfest-accepted

#48 Added Gridful Header
  Gridful Header/Fruktur-Regular.ttf
  Gridful Header/icons8-duolingo-logo.svg
  Gridful Header/index.css
  Gridful Header/index.html
  Gridful Header/name.txt
Labels: Open-Source, hacktoberfest, hacktoberfest-accepted
